### ISSUE TITLE
Dart can't find OBJLoader. 

### ISSUE THREAD

**Issue by Angergard** [threeDart/three.dart#150]
I think that OBJLoader hasn't imported JSON.

**Comment by beatgammit** [comment]
This works fine for me using git, so I can only presume OP is using the hosted package.

OBJLoader was [added in May](https://github.com/threeDart/three.dart/pull/133), which is over a year after the last pub release, so if you're tracking the hosted package, you'll have to wait for the next update (if that ever comes...).

**Comment by Angergard** [comment]
Yeah, sorry for no update. I was using pub, so it's probably what @beatgammit said.
