### ISSUE TITLE
Postprocessing

### ISSUE THREAD

**Issue by cgrabowski** [threeDart/three.dart#168]
I am working on porting the postprocessing code on this branch: https://github.com/cgrabowski/three.dart/tree/postprocessing

I have ported the shaders used by the postprocessing code and the postprocessing code. The shaders have already been merged into master. I am currently working on the examples (and getting the postprocessing code to actually work).

I did not write the original code and am unfamiliar with it. Any help would be great, especially any insight into the process of rendering WebGLRenderTargets.

**Comment by cgrabowski** [comment]
![screenshot from 2015-01-08 12 10 41](https://cloud.githubusercontent.com/assets/4088332/5666680/629ef49e-972f-11e4-9cd1-c3452f7ed537.png)

<h4>Update:</h4>
I'm postprocessing using ```WebGLRenderTargets``` and ```PlaneGeometry``` (no ```PlaneBufferGeometry``` yet). The pic shows three passes at 60 fps. Now I just need to work this into the postprocessing library.

**Comment by cgrabowski** [comment]
<h4>Update:</h4>

I got Tron Disc working. It uses two composers and seven render passes; clocking in at 60 fps.

![screenshot from 2015-01-08 19 14 15](https://cloud.githubusercontent.com/assets/4088332/5673530/2e751720-976b-11e4-8d58-3b29a36b99ca.png)

![screenshot from 2015-01-08 19 14 08](https://cloud.githubusercontent.com/assets/4088332/5673539/3c6269c8-976b-11e4-9499-213034da6c8f.png)

**Comment by robsilv** [comment]
Very cool! :-)

**Comment by cgrabowski** [comment]
https://github.com/cgrabowski/three.dart/tree/postprocessing has been merged into master.
