### ISSUE TITLE
Rendering WebGLRenderTargets and the Renderer interface

### ISSUE THREAD

**Issue by cgrabowski** [threeDart/three.dart#171]
<h4>tl;dr:</h4>
I think we should add a method to ```WebGLRenderer``` for rendering ```WebGLRenderTargets``` because this will preserve the basic rendering contract shared by all renderers that implement ```Renderer``` while exposing the ```WebGLRenderer's``` ability to render ```WebGLRenderTargets``` This is pertinent because I am currently porting the postprocessing code:

```Dart
void renderToTarget(Scene scene, Camera camera, WebGLRenderTarget renderTarget,
 [bool forceClear = false]) => _render(scene, camera, renderTarget, forceClear);
```

<h4>Discussion:</h4>
In three.js, the ```WebGLRenderer.render``` function has the following signature:

```JavaScript
render (scene, camera, renderTarget, forceClear);
```

The rest of the renderers in three.js have the following signature:

```JavaScript
render(scene, camera);
```

Of course, the ```WebGLRenderer.render``` method also implicitly supports the other signature, and in JavaScript you can simply exclude last two parameters when not rendering ```WebGLRenderTargets``` (which is actually the more typical use case), e.g.:

```Dart
renderer.render(scene, camera);
```

In three.dart we have the ```Renderer``` abstract class that creates the following render method contract:

```Dart
void render(Scene scene, Camera camera);
```

Each of the renderers in three.dart override this method. However, the private ```_render``` method in ```WebGLRenderer``` does expose (only to the library of course) the parameters for rendering ```WebGLRenderTargets```:

```Dart
_render (Scene scene, Camera camera, {renderTarget: null, forceClear: false});
```

I have been working on porting the postprocessing code, and I and anyone who wants to render ```WebGLRenderTargets``` will need to be able pass ```renderTarget``` and ```forceClear``` arguments to the ```_render``` method. Keep in mind that there is no method overloading in Dart, and adding the two extra parameters to the public render function of ```WebGLRenderer``` will cause it to no longer implement the ```Renderer``` interface

It seems to me the best way to approach this is to leave the ```WebGLRenderer.render``` method and the ```Renderer``` interface unchanged and add another method to ```WebGLRenderer```:

```Dart
void renderToTarget(Scene scene, Camera camera, WebGLRenderTarget renderTarget,
 [bool forceClear = false]) => _render(scene, camera, renderTarget, forceClear);
```
This will preserve the basic render contract shared by all renderers while exposing the ```WebGLRenderer's``` capability to render ```WebGLRenderTargets```.

**Comment by johsin18** [comment]
Sounds good to me, I would just call it `renderToTarget`to clearly make it a verb.

**Comment by cgrabowski** [comment]
Yes, ```renderToTarget``` is clearer.

**Comment by cgrabowski** [comment]
```renderToTarget``` has been added to ```WebGLRenderer```.
