### ISSUE TITLE
Hemisphere light broken

### ISSUE THREAD

**Issue by DanielJoyce** [threeDart/three.dart#175]
Other lights work fine.

        HemisphereLight sky = new HemisphereLight(0x3377FF, 0x337700, intensity: 1.0);
        sky.position.setValues(0.0, 0.0, 1000.0);
        _scene.add(sky);

Exception: Uncaught Error: The null object does not have a method 'toDouble'.

NoSuchMethodError: method not found: 'toDouble'
Receiver: null
Arguments: []
Stack Trace:
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#1      double.* (dart:core-patch/double.dart:26)
#2      WebGLRenderer.setColorLinear (package:three/src/renderers/web_gl_renderer.dart:5781:35)
#3      WebGLRenderer.setupLights (package:three/src/renderers/web_gl_renderer.dart:6036:25)
#4      WebGLRenderer.setProgram (package:three/src/renderers/web_gl_renderer.dart:5251:22)
#5      WebGLRenderer.renderBuffer (package:three/src/renderers/web_gl_renderer.dart:3681:25)
#6      WebGLRenderer.renderObjects (package:three/src/renderers/web_gl_renderer.dart:4336:23)
#7      WebGLRenderer._render (package:three/src/renderers/web_gl_renderer.dart:4208:20)
#8      WebGLRenderer.render (package:three/src/renderers/web_gl_renderer.dart:4051:50)
#9      DlpApp._render (http://localhost:8080/elements/microtome_app.dart:134:25)
#10     _animate (http://localhost:8080/elements/microtome_app.dart:130:16)
#11     _RootZone.runUnary (dart:async/zone.dart:1155)
#12     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:484)
#13     _Future._propagateToListeners (dart:async/future_impl.dart:567)
#14     _Future._complete (dart:async/future_impl.dart:348)
#15     _SyncCompleter.complete (dart:async/future_impl.dart:52)
#16     Window.animationFrame.<anonymous closure> (dart:html:32661)

**Comment by DanielJoyce** [comment]
I should add this error occurs when the scene is loaded. The snippet merely shows setting up a hemisphere light.

**Comment by johsin18** [comment]
Haven't you fixed this yourself in the meantime?

**Comment by DanielJoyce** [comment]
Yes, the fix was committed as part of my pull request that was merged in.

**Comment by DanielJoyce** [comment]
This can be closed
