### ISSUE TITLE
Alive?

### ISSUE THREAD

**Issue by SCKelemen** [threeDart/three.dart#203]
Is this project dead? there hasnt been any commits in years?

**Comment by InteLStaT** [comment]
It seems.

**Comment by PracticalCode** [comment]
Does anyone know if any developers and/or teams are working to migrate this to Dart 2.0?

**Comment by ghost** [comment]
If you want Three.js in Dart 2.0, my hack is the only hack in town:
https://github.com/exo-pla-net/threejs-dart-facade

As soon as someone does this properly, please let me know!
